version: "3.8"

services:
  backend-python:
    build: ./backend-python/
    ports:
      - "8000:8000"
    container_name: backend-python
    volumes:
      - ./logs:/app/logs
      - sqlite_data:/app

  backend-golang:
    build: ./backend-golang/
    ports:
      - "8080:8080"
    container_name: backend-golang
    volumes:
      - ./logs:/logs
      - sqlite_data:/app/data

  filebeat:
    build: ./filebeat/
    container_name: filebeat
    volumes:
      - ./logs:/src/logs
    depends_on:
      - backend-python
      - backend-golang
      - elasticsearch
      - kibana
    network_mode: "host"

  elasticsearch:
    build: ./elasticsearch/
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    build: ./kibana/
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  gateway:
    build: ./gateway
    ports:
      - "3000:80"
    depends_on:
      - backend-python
      - backend-golang
    volumes:
      - ./logs/nginx:/var/log/nginx

volumes:
  elasticsearch_data:
    driver: local

  sqlite_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/backend-python/

